export const strings = {
  navigation: {
    home: 'Файловий менеджер',
    fileEditor: 'Редактор файлу',
    itemDetails: 'Інформація',
    stats: 'Статистика сховища',
  },
  common: {
    cancel: 'Скасувати',
    create: 'Створити',
    delete: 'Видалити',
    details: 'Деталі',
    error: 'Помилка',
    save: 'Зберегти',
    loading: 'Завантаження...',
    notAvailable: 'Н/Д',
  },
  actions: {
    createFolder: '+ Папка',
    createTextFile: '+ Текстовий файл',
    refresh: 'Оновити',
    stats: 'Статистика',
    up: 'Вгору',
  },
  pathHeader: {
    currentPath: 'Поточний шлях',
    workspaceRoot: 'Коренева папка',
  },
  home: {
    loading: 'Завантаження файлової системи...',
    sectionTitle: 'Вміст папки',
    emptyTitle: 'Папка порожня',
    emptyText: 'Створіть папку або текстовий файл за допомогою кнопок вище.',
    totalSpace: 'Усього місця',
    freeSpace: 'Вільно',
    usedSpace: 'Використано',
    currentFolderSize: 'Розмір поточної папки',
    createFolderTitle: 'Створити папку',
    createFolderDescription: 'Введіть назву папки для поточної директорії.',
    createFileTitle: 'Створити текстовий файл',
    createFileDescription: 'Введіть назву файлу та, за потреби, початковий вміст. Розширення .txt буде додано автоматично.',
    folderPlaceholder: 'Наприклад: Нотатки',
    filePlaceholder: 'Наприклад: список-справ',
    fileContentPlaceholder: 'Початковий вміст файлу',
    validationError: 'Помилка перевірки',
    createFolderError: 'Не вдалося створити папку',
    createFileError: 'Не вдалося створити файл',
    deleteTitle: 'Видалення',
    deleteQuestionFolder: 'Видалити папку "{name}"?',
    deleteQuestionFile: 'Видалити файл "{name}"?',
    deleteError: 'Не вдалося видалити елемент',
    loadError: 'Не вдалося завантажити папку.',
  },
  fileListItem: {
    directory: 'Папка',
    file: 'Файл',
    directoryBadge: 'ПАП',
    fileBadge: 'ТЕК',
  },
  editor: {
    openError: 'Не вдалося відкрити файл',
    openErrorMessage: 'Не вдалося відкрити файл.',
    ok: 'Добре',
    savedTitle: 'Збережено',
    savedMessage: 'Зміни записано у файл.',
    saveError: 'Не вдалося зберегти файл',
    saveErrorMessage: 'Не вдалося зберегти файл.',
    loading: 'Відкриття файлу...',
    fullPath: 'Повний шлях',
    textContent: 'Текстовий вміст',
    placeholder: 'Введіть текст...',
    saving: 'Збереження...',
    saveChanges: 'Зберегти зміни',
  },
  details: {
    loadError: 'Не вдалося завантажити інформацію.',
    name: 'Назва',
    type: 'Тип',
    extension: 'Розширення',
    size: 'Розмір',
    lastModified: 'Дата зміни',
    createdAt: 'Дата створення',
    fullPath: 'Повний шлях',
    nestedItems: 'Вкладені елементи',
  },
  stats: {
    loadError: 'Не вдалося завантажити статистику сховища.',
    title: 'Статистика сховища',
    totalDeviceSpace: 'Усього на пристрої',
    availableSpace: 'Доступно',
    usedSpace: 'Використано',
    currentFolderSize: 'Розмір поточної папки',
    workspaceTitle: 'Робоча область застосунку',
    rootPath: 'Кореневий шлях',
    currentPath: 'Поточний шлях',
    workspaceSize: 'Розмір робочої області',
    workspaceFiles: 'Файлів у робочій області',
    workspaceFolders: 'Папок у робочій області',
    expoNoteTitle: 'Примітка Expo',
    expoNoteText:
      'Expo надає загальні показники дискового простору через `Paths.totalDiskSpace` і `Paths.availableDiskSpace`. Детальна аналітика по розділах диска недоступна у стандартному Expo, тому застосунок додатково обчислює розмір власної робочої папки.',
  },
  modal: {
    cancel: 'Скасувати',
  },
  validation: {
    nameRequired: "Назва є обов'язковою.",
    reservedNames: 'Назви "." і ".." не дозволені.',
    invalidCharacters: 'Назва містить недопустимі символи: < > : " / \\ | ? *',
    tooLong: 'Назва задовга. Використовуйте не більше 60 символів.',
    onlyTxt: 'Дозволені лише файли .txt.',
  },
  service: {
    fileSystemUnsupported: 'expo-file-system не підтримується у вебверсії. Запустіть проєкт на Android або iOS.',
    directoryDoesNotExist: 'Папка не існує.',
    parentDirectoryDoesNotExist: 'Батьківська папка не існує.',
    folderAlreadyExists: 'Папка з такою назвою вже існує.',
    fileAlreadyExists: 'Файл з такою назвою вже існує.',
    fileDoesNotExist: 'Файл не існує.',
    onlyTxtOpen: 'У редакторі можна відкривати лише файли .txt.',
    onlyTxtEdit: 'Редагувати можна лише файли .txt.',
    currentDirectoryDoesNotExist: 'Поточна папка не існує.',
    folderType: 'Папка',
    textFileType: 'Текстовий файл',
    fileType: 'Файл',
  },
};
